---
title: "NfL_analysis"
author: "Sanjay"
date: "2022-09-22"
output: html_document
---

```{r}
# load libraries 
library(metafor)
library(dplyr)
library(robumeta)
library(data.table)


```

```{r}
# read and wrangle data 

data <- read.csv('/Users/sb930/Documents/PhD/MND FTD Metaanalysis/FTD IF review - TC2.csv', header=TRUE)

# transpose then add back in row and column headers 
data_rownames = rownames(data)
data_colnames = colnames(data)
data_t <- transpose(data)
rownames(data_t) <- data_colnames
colnames(data_t) <- data_rownames
colnames(data_t) <- data_t[1,]
data_t <- data_t[-1,]
data_t <- data.frame(data_t)

# subset the dataframe to variables of interest 
data_t_rownames = rownames(data_t)
data2 <- data_t[c(9,28,84,85,91,92)]
#add row header as a column
data2$studyid = c(data_t_rownames)

# remove empty rows
data2[data2 == ""] <- NA    
dat <- subset(data2, !is.na(mean_nfl_con))

```

```{r}
# make data frame columns numeric
df2 <- mutate_all(dat, function(x) as.numeric(as.character(x)))

```



```{r}
# use escalc to calculate effect sizes 
# calculating the standardised mean difference with SMD (Hedges, 1981) 

# data=dat, m1i=mean_nfl_con, m2i=mean_nfl_ftd,

# m1i <- dat[dat$mean_nfl_con]
# m2i <- dat[dat$mean_nfl_ftd]
# sd1i <- dat[dat$SD_nfl_con]
# sd2i <- dat[dat$SD_nfl_ftd]
# n1i <- dat[dat$n_con]
# n2i <- dat[dat$n_ftd]

# dat <- escalc(data=dat, measure="SMD", m1i=m1i, m2i=m2i,
#                 sd1i=sd1i, sd2i=sd2i,
#                 n1i=n1i, n2i=n2i)

df2 <- escalc(data=df2, measure="SMD", m1i=mean_nfl_con, m2i=mean_nfl_ftd,
                sd1i=SD_nfl_con, sd2i=SD_nfl_ftd,
                n1i=n_con, n2i=n_ftd,slab=paste("ID", studyid))

df2

```

```{r}
#random effects model 
res <- rma (yi, vi, method="REML", data=df2)
```


```{r}
# construct forest plot 

forest(res, addfit=FALSE) 

```



```{r}
# construct funnel plot 

funnel(res) 

```

```{r}
# heterogeneity measures

res.CA  <- rma(yi, vi, method="HE", data=df2)

res.CA

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
