
---
title: "nfl_analysis_v2.Rmd"
author: "Sanjay"
date: "24/12/2022"
output: html_document
---

# Step 1: run a loop for CHI3L for controls to predict mean and sd where mdian, IQR, range available

```{r}
# Step 3 run a loop for all papers for a specific immune marker (do for controls first) 

# Initial part of step 2 is the same - data wrangling to subset immune marker nfl

library(readxl)
library(data.table)
library(estmeansd)
library (dplyr)

# Create a dataframe with some subsetted data from FTD meta-analysis

results <-read_excel("/Users/sb930/Downloads/221225_FTD_IF_review.xlsx", sheet = 6)
# sheet 10 is final sheet with Yusuf's results. Use mine for now

results

results2 <- transpose(results)


# transpose then add back in row and column headers 
data_rownames = rownames(results)
data_colnames = colnames(results)
data_t <- transpose(results)
rownames(data_t) <- data_colnames
colnames(data_t) <- data_rownames
colnames(data_t) <- data_t[1,]
data_t <- data_t[-1,]
data_t <- data.frame(data_t)

# subset the dataframe to variables of interest 
# for each immune marker, choose the appropriate rows - can hover over R to get the column number when viewing
data_t_rownames = rownames(data_t)

nfl_df2_con <- data_t %>%
  select(n_con, med_nfl_con, l_iqr_nfl_con, u_iqr_nfl_con, l_range_nfl_con, u_range_nfl_con)

nfl_df2_ftd <- data_t %>%
  select(n_ftd, med_nfl_ftd, l_iqr_nfl_ftd, u_iqr_nfl_ftd, l_range_nfl_ftd, u_range_nfl_ftd)

# Alternative way of subsetting columns manually rather than using dplyr
# nfl_df2_con <- data_t[c(10,346,347,348,349,350)]
# nfl_df2_ftd <- data_t[c(29,353,354,355,356,357)]

#add row header as a column
nfl_df2_con$studyid = c(data_t_rownames)
nfl_df2_ftd$studyid = c(data_t_rownames)

```


```{r}

# if statement based on step 2 for complete cases only (i.e. median, range and IQR) for controls

columns <- c("mean","sd","study.id","n_con")
nfl_df4_completes_con <- (matrix(nrow = 0, ncol = length(columns)))
colnames(nfl_df4_completes_con) <- columns

nfl_df3_completes_con <- subset(nfl_df2_con, complete.cases(nfl_df2_con[, c("l_range_nfl_con", "l_iqr_nfl_con", "u_iqr_nfl_con", "u_range_nfl_con")]))

# Loop through all rows of the data frame "data2"
for (i in 1:nrow(nfl_df3_completes_con)) {
  # Extract the current row
  row <- nfl_df3_completes_con[i, ]
  
  # Compute the mean and standard deviation using the qe.mean.sd() function
    meansd <- qe.mean.sd(min.val = as.numeric(row$l_range_nfl_con), q1.val = as.numeric(row$l_iqr_nfl_con), med.val = as.numeric(row$med_nfl_con), q3.val = as.numeric(row$u_iqr_nfl_con), max.val = as.numeric(row$u_range_nfl_con), n = as.numeric(row$n_con))
  
  # Store the results in the results data frame
  # nfl_df4_completes_con <- cbind(data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid))
  nfl_df4_completes_con <- rbind(nfl_df4_completes_con, data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid, n_con = row$n_con))
}
  
print(nfl_df4_completes_con)





```

```{r}
# now loop through the incomplete cases for controls

columns <- c("mean","sd","study.id","n_con")
nfl_df4_incompletes1_con <- (matrix(nrow = 0, ncol = length(columns)))
colnames(nfl_df4_incompletes1_con) <- columns
nfl_df4_incompletes2_con <- (matrix(nrow = 0, ncol = length(columns)))
colnames(nfl_df4_incompletes2_con) <- columns
nfl_df4_incompletes3_con <- (matrix(nrow = 0, ncol = length(columns)))
colnames(nfl_df4_incompletes3_con) <- columns
nfl_df4_incompletes_con <- (matrix(nrow = 0, ncol = length(columns)))
colnames(nfl_df4_incompletes_con) <- columns

# select median and IQR columns then remove range columns to prevent estmeansd errors 
nfl_df3_incompletes1_con <- subset(nfl_df2_con, is.na(l_range_nfl_con) & is.na(u_range_nfl_con) & !is.na(med_nfl_con) & !is.na(l_iqr_nfl_con) & !is.na(u_iqr_nfl_con))
nfl_df3_incompletes1_con <- subset (nfl_df3_incompletes1_con, select = -c(l_range_nfl_con, u_range_nfl_con))

# select median, IQR and range columns 
nfl_df3_incompletes2_con <- subset(nfl_df2_con, !is.na(l_range_nfl_con) & !is.na(u_range_nfl_con) & !is.na(med_nfl_con) & !is.na(l_iqr_nfl_con) & !is.na(u_iqr_nfl_con))

# select median and range columns then remove IQR columns to prevent estmeansd errors 
nfl_df3_incompletes3_con <- subset(nfl_df2_con, !is.na(l_range_nfl_con) & !is.na(u_range_nfl_con) & !is.na(med_nfl_con) & is.na(l_iqr_nfl_con) & is.na(u_iqr_nfl_con))

# first loop for median and IQR

for (i in 1:nrow(nfl_df3_incompletes1_con)) {
  if (nrow(nfl_df3_incompletes1_con) == 0) {
    # If the subset command returned no values, skip the rest of the code chunk
    next
  } else {
    #for (i in 1:nrow(nfl_df3_incompletes1_con)) {
      print(i)  # Debug statement
      # Extract the current row
      row <- nfl_df3_incompletes1_con[i, ]
    
      # Compute the mean and standard deviation using the qe.mean.sd() function
        meansd <- qe.mean.sd(q1.val = as.numeric(row$l_iqr_nfl_con), med.val = as.numeric(row$med_nfl_con), q3.val = as.numeric(row$u_iqr_nfl_con), n = as.numeric(row$n_con))
    
      # # Store the results in the results data frame
      # nfl_df4_incompletes_con <- cbind(data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid))
        # Store the results in the results data frame
      nfl_df4_incompletes1_con <- rbind(nfl_df4_incompletes1_con, data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid, n_con = row$n_con))
    }
  }
#}
    
print(nfl_df4_incompletes1_con)

# second loop for median, IQR and range 

for (i in 1:nrow(nfl_df3_incompletes2_con)) {
  if (nrow(nfl_df3_incompletes2_con) == 0) {
    # If the subset command returned no values, skip the rest of the code chunk
    next
  } else {
    #for (i in 1:nrow(nfl_df3_incompletes2_con)) {
      print(i)  # Debug statement
      # Extract the current row
      row <- nfl_df3_incompletes2_con[i, ]
    
      # Compute the mean and standard deviation using the qe.mean.sd() function
        meansd <- qe.mean.sd(min.val = as.numeric(row$l_range_nfl_con), q1.val = as.numeric(row$l_iqr_nfl_con), med.val = as.numeric(row$med_nfl_con), q3.val = as.numeric(row$u_iqr_nfl_con), max.val = as.numeric(row$u_range_nfl_con), n = as.numeric(row$n_con))
    
      # # Store the results in the results data frame
      # nfl_df4_incompletes_con <- cbind(data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid))
        # Store the results in the results data frame
      nfl_df4_incompletes2_con <- rbind(nfl_df4_incompletes2_con, data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid, n_con = row$n_con))
  }
}
  
print(nfl_df4_incompletes2_con)  

# third loop for median and range 

for (i in 1:nrow(nfl_df3_incompletes3_con)) {
  if (nrow(nfl_df3_incompletes3_con) == 0) {
    # If the subset command returned no values, skip the rest of the code chunk
    next
  } else {
    # for (i in 1:nrow(nfl_df3_incompletes3_con)) {
      print(i)  # Debug statement
      # Extract the current row
      row <- nfl_df3_incompletes3_con[i, ]
    
      # Compute the mean and standard deviation using the qe.mean.sd() function
        meansd <- qe.mean.sd(min.val = as.numeric(row$l_range_nfl_con), med.val = as.numeric(row$med_nfl_con), max.val = as.numeric(row$u_range_nfl_con), n = as.numeric(row$n_con))
    
      # # Store the results in the results data frame
      # nfl_df4_incompletes_con <- cbind(data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid))
        # Store the results in the results data frame
      nfl_df4_incompletes3_con <- rbind(nfl_df4_incompletes3_con, data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid, n_con = row$n_con))
  }
}
  
print(nfl_df4_incompletes3_con)  

# Bind the rows of the three tables together
nfl_df4_incompletes_con <- rbind(nfl_df4_incompletes1_con, nfl_df4_incompletes2_con, nfl_df4_incompletes3_con)

nfl_df4_incompletes_con$sd <- format(as.numeric(nfl_df4_incompletes_con$sd), scientific = FALSE)

print(nfl_df4_incompletes_con)  

```



```{r}
# Code chunk commented out because it doesn't work 

# # now loop through the incomplete cases for controls
# 
# columns <- c("mean","sd","study.id","n_con")
# nfl_df4_incompletes_con <- (matrix(nrow = 0, ncol = length(columns)))
# colnames(nfl_df4_incompletes_con) <- columns
# 
# 
# nfl_df3_con <- subset(nfl_df2_con, is.na(l_range_nfl_con) & is.na(u_range_nfl_con) & !is.na(med_nfl_con))
# nfl_df3_con <- nfl_df3_incompletes_con <- subset (nfl_df3_con, select = -l_range_nfl_con)
# nfl_df3_incompletes_con <- subset (nfl_df3_incompletes_con,  select = -u_range_nfl_con)
# 
# 
# if (nrow(subset_df) == 0) {
#   # If the subset command returned no values, skip the rest of the code chunk
#   next
# } else {
#   # Rest of the code chunk goes here...
# }
# 
# 
# subset(nfl_df2_con, is.na(l_range_nfl_con) & is.na(u_range_nfl_con) & !is.na(med_nfl_con) & !is.na(l_iqr_nfl_con) & !is.na(u_iqr_nfl_con))
# 
# subset(nfl_df2_con, !is.na(l_range_nfl_con) & !is.na(u_range_nfl_con) & !is.na(med_nfl_con) & !is.na(l_iqr_nfl_con) & !is.na(u_iqr_nfl_con))
# 
# subset(nfl_df2_con, !is.na(l_range_nfl_con) & !is.na(u_range_nfl_con) & !is.na(med_nfl_con) & is.na(l_iqr_nfl_con) & is.na(u_iqr_nfl_con))
# 
# 
# 
# 
# for (i in 1:nrow(nfl_df3_incompletes_con)) {
#   print(i)  # Debug statement
#   # Extract the current row
#   row <- nfl_df3_incompletes_con[i, ]
#   
#   # Compute the mean and standard deviation using the qe.mean.sd() function
#     meansd <- qe.mean.sd(q1.val = as.numeric(row$l_iqr_nfl_con), med.val = as.numeric(row$med_nfl_con), q3.val = as.numeric(row$u_iqr_nfl_con), n = as.numeric(row$n_con))
#   
#   # # Store the results in the results data frame
#   # nfl_df4_incompletes_con <- cbind(data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid))
#     # Store the results in the results data frame
#   nfl_df4_incompletes_con <- rbind(nfl_df4_incompletes_con, data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid, n_con = row$n_con))
# }
#   
# print(nfl_df4_incompletes_con)

```

```{r}
# Step 3 final part a - create combined dataframe of estimated values

# Combine the data frames
nfl_df4_all_con <- rbind(nfl_df4_completes_con, nfl_df4_incompletes_con)

# Order the data frame by the "study.id" column
nfl_df4_all_con <- nfl_df4_all_con[order(nfl_df4_all_con$study.id),]

```


```{r}
# Step 3 final part b - merge estimated values with extracted values

# Subset data_t to include only rows where "mean_nfl_con" and "SD_nfl_con" have a value
data_t_nfl_con <- data_t[!is.na(data_t$mean_nfl_con) & !is.na(data_t$SD_nfl_con),]

# Extract only the "mean_nfl_con" and "SD_nfl_con" columns
data_t_nfl_con <- data_t_nfl_con[, c("mean_nfl_con", "SD_nfl_con", "n_con")]

# Extract the row names from data_t
row_names <- rownames(data_t_nfl_con)

# Create a "study.id" column in data_t_nfl_con using the row names
data_t_nfl_con$study.id <- row_names

# Rename the "mean" column to "mean_nfl_con"
names(nfl_df4_all_con)[names(nfl_df4_all_con) == "mean"] <- "mean_nfl_con"

# Rename the "sd" column to "SD_nfl_con"
names(nfl_df4_all_con)[names(nfl_df4_all_con) == "sd"] <- "SD_nfl_con"

# Add column "value" to both tables so source of mean and sd is clear
# Add a "value" column to the nfl_df4_all_con data frame with estimated
nfl_df4_all_con$value <- "estimated"
# Add a "value" column to the data_t_nfl_con data frame with extracted
data_t_nfl_con$value <- "extracted"


# Combine data_t_nfl_con with nfl_df4_all_con
nfl_combined_con <- rbind(data_t_nfl_con, nfl_df4_all_con)

# Reorder the rows based on the "studyid" column
nfl_combined_con <- nfl_combined_con[order(nfl_combined_con$study.id),]

# For rows with the same "studyid" value, use the values from data_t_nfl_con
nfl_combined_con <- unique(nfl_combined_con, by = "studyid", fromLast = TRUE)


```


# Step 2 add repeat for ftd 

```{r}

# if statement based on step 2 for comple cases only (i.e. median, range and IQR) for controls

columns <- c("mean","sd","study.id", "n_ftd")
nfl_df4_completes_ftd <- (matrix(nrow = 0, ncol = length(columns)))
colnames(nfl_df4_completes_ftd) <- columns

nfl_df3_completes_ftd <- subset(nfl_df2_ftd, complete.cases(nfl_df2_ftd[, c("l_range_nfl_ftd", "l_iqr_nfl_ftd", "u_iqr_nfl_ftd", "u_range_nfl_ftd")]))

# Loop through all rows of the data frame "data2"
for (i in 1:nrow(nfl_df3_completes_ftd)) {
  # Extract the current row
  row <- nfl_df3_completes_ftd[i, ]
  
  # Compute the mean and standard deviation using the qe.mean.sd() function
    meansd <- qe.mean.sd(min.val = as.numeric(row$l_range_nfl_ftd), q1.val = as.numeric(row$l_iqr_nfl_ftd), med.val = as.numeric(row$med_nfl_ftd), q3.val = as.numeric(row$u_iqr_nfl_ftd), max.val = as.numeric(row$u_range_nfl_ftd), n = as.numeric(row$n_ftd))
  
  # Store the results in the results data frame
  # nfl_df4_completes_ftd <- cbind(data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid))
  nfl_df4_completes_ftd <- rbind(nfl_df4_completes_ftd, data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid, n_ftd= row$n_ftd))
}
  
print(nfl_df4_completes_ftd)

```

```{r}
# now loop through the incomplete cases for controls

columns <- c("mean","sd","study.id","n_ftd")
nfl_df4_incompletes1_ftd <- (matrix(nrow = 0, ncol = length(columns)))
colnames(nfl_df4_incompletes1_ftd) <- columns
nfl_df4_incompletes2_ftd <- (matrix(nrow = 0, ncol = length(columns)))
colnames(nfl_df4_incompletes2_ftd) <- columns
nfl_df4_incompletes3_ftd <- (matrix(nrow = 0, ncol = length(columns)))
colnames(nfl_df4_incompletes3_ftd) <- columns
nfl_df4_incompletes_ftd <- (matrix(nrow = 0, ncol = length(columns)))
colnames(nfl_df4_incompletes_ftd) <- columns

# select median and IQR columns then remove range columns to prevent estmeansd errors 
nfl_df3_incompletes1_ftd <- subset(nfl_df2_ftd, is.na(l_range_nfl_ftd) & is.na(u_range_nfl_ftd) & !is.na(med_nfl_ftd) & !is.na(l_iqr_nfl_ftd) & !is.na(u_iqr_nfl_ftd))
nfl_df3_incompletes1_ftd <- subset (nfl_df3_incompletes1_ftd, select = -c(l_range_nfl_ftd, u_range_nfl_ftd))

# select median, IQR and range columns 
nfl_df3_incompletes2_ftd <- subset(nfl_df2_ftd, !is.na(l_range_nfl_ftd) & !is.na(u_range_nfl_ftd) & !is.na(med_nfl_ftd) & !is.na(l_iqr_nfl_ftd) & !is.na(u_iqr_nfl_ftd))

# select median and range columns then remove IQR columns to prevent estmeansd errors 
nfl_df3_incompletes3_ftd <- subset(nfl_df2_ftd, !is.na(l_range_nfl_ftd) & !is.na(u_range_nfl_ftd) & !is.na(med_nfl_ftd) & is.na(l_iqr_nfl_ftd) & is.na(u_iqr_nfl_ftd))

# first loop for median and IQR

if (nrow(nfl_df3_incompletes1_ftd) == 0) {
  # If the subset command returned no values, skip the rest of the code chunk
  next
} else {
  for (i in 1:nrow(nfl_df3_incompletes1_ftd)) {
    print(i)  # Debug statement
    # Extract the current row
    row <- nfl_df3_incompletes1_ftd[i, ]
  
    # Compute the mean and standard deviation using the qe.mean.sd() function
      meansd <- qe.mean.sd(q1.val = as.numeric(row$l_iqr_nfl_ftd), med.val = as.numeric(row$med_nfl_ftd), q3.val = as.numeric(row$u_iqr_nfl_ftd), n = as.numeric(row$n_ftd))
  
    # # Store the results in the results data frame
    # nfl_df4_incompletes_ftd <- cbind(data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid))
      # Store the results in the results data frame
    nfl_df4_incompletes1_ftd <- rbind(nfl_df4_incompletes1_ftd, data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid, n_ftd = row$n_ftd))
  }
}
  
print(nfl_df4_incompletes1_ftd)

# second loop for median, IQR and range 

if (nrow(nfl_df3_incompletes2_ftd) == 0) {
  # If the subset command returned no values, skip the rest of the code chunk
  next
} else {
  for (i in 1:nrow(nfl_df3_incompletes2_ftd)) {
    print(i)  # Debug statement
    # Extract the current row
    row <- nfl_df3_incompletes2_ftd[i, ]
  
    # Compute the mean and standard deviation using the qe.mean.sd() function
      meansd <- qe.mean.sd(min.val = as.numeric(row$l_range_nfl_ftd), q1.val = as.numeric(row$l_iqr_nfl_ftd), med.val = as.numeric(row$med_nfl_ftd), q3.val = as.numeric(row$u_iqr_nfl_ftd), max.val = as.numeric(row$u_range_nfl_ftd), n = as.numeric(row$n_ftd))
  
    # # Store the results in the results data frame
    # nfl_df4_incompletes_ftd <- cbind(data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid))
      # Store the results in the results data frame
    nfl_df4_incompletes2_ftd <- rbind(nfl_df4_incompletes2_ftd, data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid, n_ftd = row$n_ftd))
  }
}
  
print(nfl_df4_incompletes2_ftd)  

# third loop for median and range 

if (nrow(nfl_df3_incompletes3_ftd) == 0) {
  # If the subset command returned no values, skip the rest of the code chunk
  next
} else {
  for (i in 1:nrow(nfl_df3_incompletes3_ftd)) {
    print(i)  # Debug statement
    # Extract the current row
    row <- nfl_df3_incompletes3_ftd[i, ]
  
    # Compute the mean and standard deviation using the qe.mean.sd() function
      meansd <- qe.mean.sd(min.val = as.numeric(row$l_range_nfl_ftd), med.val = as.numeric(row$med_nfl_ftd), max.val = as.numeric(row$u_range_nfl_ftd), n = as.numeric(row$n_ftd))
  
    # # Store the results in the results data frame
    # nfl_df4_incompletes_ftd <- cbind(data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid))
      # Store the results in the results data frame
    nfl_df4_incompletes3_ftd <- rbind(nfl_df4_incompletes3_ftd, data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid, n_ftd = row$n_ftd))
  }
}
  
print(nfl_df4_incompletes3_ftd)  

# Bind the rows of the three tables together
nfl_df4_incompletes_ftd <- rbind(nfl_df4_incompletes1_ftd, nfl_df4_incompletes2_ftd, nfl_df4_incompletes3_ftd)

print(nfl_df4_incompletes_ftd)  

```



```{r}
# commented out because code doesn't work

# # now loop through the incomplete cases for ftd
# 
# columns <- c("mean","sd","study.id","n_ftd")
# nfl_df4_incompletes_ftd <- (matrix(nrow = 0, ncol = length(columns)))
# colnames(nfl_df4_incompletes_ftd) <- columns
# 
# 
# nfl_df3_ftd <- subset(nfl_df2_ftd, is.na(l_range_nfl_ftd) & is.na(u_range_nfl_ftd) & !is.na(med_nfl_ftd))
# nfl_df3_incompletes_ftd <- subset (nfl_df3_ftd, select = -l_range_nfl_ftd)
# nfl_df3_incompletes_ftd <- subset (nfl_df3_incompletes_ftd,  select = -u_range_nfl_ftd)
# 
# for (i in 1:nrow(nfl_df3_incompletes_ftd)) {
#   print(i)  # Debug statement
#   # Extract the current row
#   row <- nfl_df3_incompletes_ftd[i, ]
#   
#   # Compute the mean and standard deviation using the qe.mean.sd() function
#     meansd <- qe.mean.sd(q1.val = as.numeric(row$l_iqr_nfl_ftd), med.val = as.numeric(row$med_nfl_ftd), q3.val = as.numeric(row$u_iqr_nfl_ftd), n = as.numeric(row$n_ftd))
#   
#   # # Store the results in the results data frame
#   # nfl_df4_incompletes_ftd <- cbind(data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid))
#     # Store the results in the results data frame
#   nfl_df4_incompletes_ftd <- rbind(nfl_df4_incompletes_ftd, data.frame(mean = meansd$est.mean, sd = meansd$est.sd, study.id = row$studyid, n_ftd = row$n_ftd))
# }
#   
# print(nfl_df4_incompletes_ftd)

```

```{r}
# Step 3 final part a - create combined dataframe of estimated values

# Combine the data frames
nfl_df4_all_ftd <- rbind(nfl_df4_completes_ftd, nfl_df4_incompletes_ftd)

# Order the data frame by the "study.id" column
nfl_df4_all_ftd <- nfl_df4_all_ftd[order(nfl_df4_all_ftd$study.id),]

```


```{r}
# Step 3 final part b - merge estimated values with extracted values

# Subset data_t to include only rows where "mean_nfl_ftd" and "SD_nfl_ftd" have a value
data_t_nfl_ftd <- data_t[!is.na(data_t$mean_nfl_ftd) & !is.na(data_t$SD_nfl_ftd),]

# Extract only the "mean_nfl_ftd" and "SD_nfl_ftd" columns
data_t_nfl_ftd <- data_t_nfl_ftd[, c("mean_nfl_ftd", "SD_nfl_ftd", "n_ftd")]

# Extract the row names from data_t
row_names <- rownames(data_t_nfl_ftd)

# Create a "study.id" column in data_t_nfl_ftd using the row names
data_t_nfl_ftd$study.id <- row_names

# Rename the "mean" column to "mean_nfl_ftd"
names(nfl_df4_all_ftd)[names(nfl_df4_all_ftd) == "mean"] <- "mean_nfl_ftd"

# Rename the "sd" column to "SD_nfl_ftd"
names(nfl_df4_all_ftd)[names(nfl_df4_all_ftd) == "sd"] <- "SD_nfl_ftd"

# Add column "value" to both tables so source of mean and sd is clear
# Add a "value" column to the nfl_df4_all_ftd data frame with estimated
nfl_df4_all_ftd$value <- "estimated"
# Add a "value" column to the data_t_nfl_ftd data frame with extracted
data_t_nfl_ftd$value <- "extracted"


# Combine data_t_nfl_ftd with nfl_df4_all_ftd
nfl_combined_ftd <- rbind(data_t_nfl_ftd, nfl_df4_all_ftd)

# Reorder the rows based on the "studyid" column
nfl_combined_ftd <- nfl_combined_ftd[order(nfl_combined_ftd$study.id),]

# For rows with the same "studyid" value, use the values from data_t_nfl_ftd
nfl_combined_ftd <- unique(nfl_combined_ftd, by = "studyid", fromLast = TRUE)

```


# Step 3 add effect size calculations

```{r}
# load libraries 
library(metafor)
library(dplyr)
library(robumeta)
library(data.table)
```



```{r}
# combine control and FTD data frames 
nfl_combined <- full_join(nfl_combined_con, nfl_combined_ftd, by="study.id")

# make data frame columns except study id numeric
nfl_combined <- mutate_at(nfl_combined, vars(contains("_")), function(x) as.numeric(as.character(x)))

```


```{r}
# use escalc to calculate effect sizes 

# change name of immune marker for each of the terms

df2 <- escalc(data=nfl_combined, measure="SMD", m2i=mean_nfl_con, m1i=mean_nfl_ftd,
                sd2i=SD_nfl_con, sd1i=SD_nfl_ftd,
                n2i=n_con, n1i=n_ftd,slab=paste("ID", study.id))

df2

```
```{r}
#random effects model 
res <- rma (yi, vi, method="REML", data=df2)
```


```{r}
# construct forest plot 

forest(res) 

```


```{r}
# construct funnel plot 

funnel(res) 

```

```{r}
# heterogeneity measures

res.CA  <- rma(yi, vi, method="HE", data=df2)

res.CA

```
